# Generated by Django 4.1.1 on 2022-10-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '0002_alter_pelicula_descripcion_alter_pelicula_sipnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ManyToManyField(blank=True, to='peliculas.pelicula')),
            ],
        ),
    ]
